name: 'Get Version'
description: Get Version from the project

inputs:
  stack:
    description: 'The workflow to get the version for (e.g. java or node)'
    required: true

outputs:
    version:
        description: 'The current version from the pom.xml or package.json'
        value: ${{ steps.read.outputs.version }}
    is_snapshot:
        description: 'Whether the current version is a snapshot version'
        value: ${{ steps.read.outputs.is_snapshot }}
    base_version:
        description: 'Base version without the -SNAPSHOT suffix'
        value: ${{ steps.read.outputs.base_version }}
    major:
        description: 'Major version number'
        value: ${{ steps.read.outputs.major }}
    minor:
        description: 'Minor version number'
        value: ${{ steps.read.outputs.minor }}
    patch:
        description: 'Patch version number'
        value: ${{ steps.read.outputs.patch }}


runs:
  using: 'composite'
  steps:
    - id: read
      shell: bash
      env:
        STACK: ${{ inputs.stack }}
      run: ${{ github.action_path }}/get-version.sh